image: registry.gitlab.com/stuko/ovito/linux_build:latest

build_linux_python3:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DPYTHON_EXECUTABLE=/usr/bin/python3.5
           -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j3 install
      - ctest --output-on-failure
      - linkchecker --check-extern ../install/share/ovito/doc/manual/html/index.html
           --ignore-url=https://dx.doi.org/10.1088/0965-0393/24/5/055007
           --ignore-url=http://stacks.iop.org/0965-0393/18/015012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/3/035012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/4/045021
           --ignore-url=http://dx.doi.org/10.1038/nature04421

build_linux_python2:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DPYTHON_EXECUTABLE=/usr/bin/python2.7
           -DPYTHON_INCLUDE_DIR=/usr/include/python2.7
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j3 install
      - ctest --output-on-failure

# This pipeline job generates the redistributable program package for Linux.
build_linux_package:
   stage: build
   tags:
      - linux_vm
   script:
      - mkdir build
      - cd build
      - export LD_LIBRARY_PATH=$HOME/progs/libav/lib:$LD_LIBRARY_PATH
      - echo $PWD
      - $HOME/progs/cmake-3.6.3-Linux-x86_64/bin/cmake \
            -DOVITO_BUILD_DOCUMENTATION=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../release_install \
            -DOVITO_REDISTRIBUTABLE_PACKAGE=ON \
            -DOVITO_DOUBLE_PRECISION_FP=ON \
            -DBOOST_ROOT=$HOME/progs/boost \
            -DHDF5_DIR=$HOME/progs/hdf5/share/cmake \
            -DnetCDF_DIR=$HOME/progs/netcdf/lib/cmake/netCDF \
            -DPYTHON_EXECUTABLE=$HOME/progs/python/bin/python3 \
            -DPYTHON_LIBRARY=$HOME/progs/python/lib/libpython3.6m.so.1.0 \
            -DPYTHON_INCLUDE_DIR=$HOME/progs/python/include/python3.6m \
            -DCMAKE_PREFIX_PATH=$HOME/progs/qt5/ \
            -DQSCINTILLA_INCLUDE_DIR=$HOME/progs/QScintilla_gpl-2.9.3/Qt4Qt5/ \
            -DQSCINTILLA_LIBRARY=$HOME/progs/QScintilla_gpl-2.9.3/Qt4Qt5/libqscintilla2.so.12 \
            -DLIBAV_INCLUDE_DIR=$HOME/progs/libav/include \
            -DLIBAV_LIBRARY_DIR=$HOME/progs/libav/lib \
            -DOVITO_BUILD_PLUGIN_OSPRAY=ON \
            -Dospray_DIR=$HOME/progs/ospray_install/lib/cmake/ospray-1.8.4 \
            -Dembree_DIR=$HOME/progs/embree_install/lib/cmake/embree-3.5.2 \
            -DISPC_EXECUTABLE=$HOME/progs/ispc-v1.9.2-linux/ispc \
            -DTBB_INCLUDE_DIR=$HOME/progs/tbb2018_20170919oss/include/ \
            -DTBB_LIBRARY=$HOME/progs/tbb2018_20170919oss/lib/intel64/gcc4.7/libtbb.so \
            -DTBB_LIBRARY_MALLOC=$HOME/progs/tbb2018_20170919oss/lib/intel64/gcc4.7/libtbbmalloc.so \
            -DTBB_DIR=$HOME/progs/tbb2018_20170919oss/cmake \
            -DTBB_ROOT=$HOME/progs/tbb2018_20170919oss \
            -DLIBSSH_INCLUDE_DIR=$HOME/progs/libssh_install/include \
            -DLIBSSH_LIBRARY=$HOME/progs/libssh_install/lib/libssh.so \
            ..
      - make

# build_macos_release:
#    stage: build
#    tags:
#       - macos
#    script:
#       - mkdir build
#       - cd build
#       - export MACOSX_DEPLOYMENT_TARGET=10.9
#       - echo $PWD
#       - cmake
#          -DOVITO_BUILD_DOCUMENTATION=ON
#          -DCMAKE_BUILD_TYPE=Release
#          -DOVITO_REDISTRIBUTABLE_PACKAGE=ON
#          -DCMAKE_PREFIX_PATH=$HOME/progs/Qt/5.9.5/clang_64/
#          -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
#          -DPYTHON_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m
#          -DPYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6.dylib
#          -DLIBAV_INCLUDE_DIR=$HOME/progs/libav/include
#          -DLIBAV_LIBRARY_DIR=$HOME/progs/libav/lib
#          -DQSCINTILLA_INCLUDE_DIR=$HOME/progs/QScintilla_gpl-2.10.4/Qt4Qt5
#          -DQSCINTILLA_LIBRARY=$HOME/progs/QScintilla_gpl-2.10.4/Qt4Qt5/libqscintilla2_qt5.dylib
#          -DnetCDF_DIR=$HOME/progs/netcdf/lib/cmake/netCDF
#          -DHDF5_DIR=$HOME/progs/hdf5/share/cmake/hdf5
#          -DOVITO_BUILD_PLUGIN_OSPRAY=ON
#          -Dospray_DIR=$HOME/progs/ospray_install/lib/cmake/ospray-1.6.0
#          -Dembree_DIR=$HOME/progs/embree_install/lib/cmake/embree-3.2.0
#          -DISPC_EXECUTABLE=$HOME/progs/ispc-v1.9.2-osx/ispc
#          -DTBB_ROOT=$HOME/progs/tbb2018_20180312oss
#          ..
#       - make -j2
#       - ctest --output-on-failure