image: registry.gitlab.com/stuko/ovito/linux_build:latest

build_linux_python3:
   stage: build
   tags:
      - linux
   script:
      - /usr/bin/python3.5 -m pip install --upgrade --user numpy
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DPYTHON_EXECUTABLE=/usr/bin/python3.5
           -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j3 install
      - ctest --output-on-failure
      - linkchecker --check-extern ../install/share/ovito/doc/manual/html/index.html
           --ignore-url=https://dx.doi.org/10.1088/0965-0393/24/5/055007
           --ignore-url=http://stacks.iop.org/0965-0393/18/015012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/3/035012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/4/045021
           --ignore-url=http://dx.doi.org/10.1038/nature04421

build_linux_python2:
   stage: build
   tags:
      - linux
   script:
      - /usr/bin/python2.7 -m pip install --upgrade --user numpy
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DPYTHON_EXECUTABLE=/usr/bin/python2.7
           -DPYTHON_INCLUDE_DIR=/usr/include/python2.7
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j3 install
      - ctest --output-on-failure

# This pipeline job generates the redistributable program package for Linux.
build_linux_package:
   stage: build
   tags:
      - linux_vm
   only:
      refs:
         - master
         - schedules
   artifacts:
      paths:
         - build/ovito-*.tar.gz
   script:
      - scl enable devtoolset-7 bash
      - source /opt/rh/devtoolset-7/enable
      - mkdir build
      - cd build
      - export LD_LIBRARY_PATH=$HOME/progs/libav/lib:$LD_LIBRARY_PATH
      - cmake
         -DOVITO_BUILD_DOCUMENTATION=ON
         -DCMAKE_BUILD_TYPE=Release
         -DCMAKE_INSTALL_PREFIX=../release_install
         -DOVITO_REDISTRIBUTABLE_PACKAGE=ON
         -DOVITO_DOUBLE_PRECISION_FP=ON
         -DOVITO_BUILD_PLUGIN_OSPRAY=ON
         -DHDF5_DIR=$HOME/progs/hdf5/share/cmake/hdf5
         -DnetCDF_DIR=`echo $HOME/progs/netcdf/lib*/cmake/netCDF`
         -DPYTHON_EXECUTABLE=$HOME/progs/python/bin/python3
         -DPYTHON_LIBRARY=`echo $HOME/progs/python/lib/libpython*.so.*`
         -DPYTHON_INCLUDE_DIR=`echo $HOME/progs/python/include/python*`
         -DCMAKE_PREFIX_PATH=$HOME/progs/qt5/
         -DQSCINTILLA_INCLUDE_DIR=`echo $HOME/progs/QScintilla_gpl-*`/Qt4Qt5/
         -DQSCINTILLA_LIBRARY=`echo $HOME/progs/QScintilla_gpl-*/Qt4Qt5/libqscintilla2_qt5.so.*`
         -DLIBAV_INCLUDE_DIR=$HOME/progs/libav/include
         -DLIBAV_LIBRARY_DIR=$HOME/progs/libav/lib
         -Dospray_DIR=`echo $HOME/progs/ospray_install/lib*/cmake/ospray-*`
         -Dembree_DIR=`echo $HOME/progs/embree_install/lib*/cmake/embree-*`
         -DISPC_EXECUTABLE=`echo $HOME/progs/ispc-*-linux/ispc`
         -DTBB_INCLUDE_DIR=`echo $HOME/progs/tbb*oss`/include/
         -DTBB_LIBRARY=`echo $HOME/progs/tbb*oss`/lib/intel64/gcc4.7/libtbb.so
         -DTBB_LIBRARY_MALLOC=`echo $HOME/progs/tbb*oss`/lib/intel64/gcc4.7/libtbbmalloc.so
         -DTBB_DIR=`echo $HOME/progs/tbb*oss`/cmake
         -DTBB_ROOT=`echo $HOME/progs/tbb*oss`
         -DLIBSSH_INCLUDE_DIR=$HOME/progs/libssh/include
         -DLIBSSH_LIBRARY=$HOME/progs/libssh/lib/libssh.so
         -DBOOST_INCLUDEDIR=$HOME/progs/boost_1_70_0
         ..
      - make
      - cpack
      - sshpass -v -e sftp ovito.org:testing/ <<< $'put ovito-*.tar.gz'

# This pipeline job generates the redistributable program package for MacOS.
build_macos_package:
   stage: build
   tags:
      - macos_vm
   only:
      refs:
         - master
         - schedules
   artifacts:
      paths:
         - build/ovito-*.dmg
   script:
      - security unlock-keychain -p "vmpassword" login.keychain
      - git describe
      - mkdir build
      - cd build
      - cmake
         -DOVITO_BUILD_DOCUMENTATION=ON
         -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12
         -DCMAKE_BUILD_TYPE=Release
         -DOVITO_REDISTRIBUTABLE_PACKAGE=ON
         -DOVITO_DOUBLE_PRECISION_FP=ON
         -DOVITO_BUILD_PLUGIN_OSPRAY=ON
         -DCMAKE_INSTALL_PREFIX=../release_install
         -DCMAKE_PREFIX_PATH=`echo $HOME/Qt/5.*.*/clang_64/`
         -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
         -DPYTHON_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m
         -DPYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib
         -DLIBAV_INCLUDE_DIR=$HOME/progs/libav/include
         -DLIBAV_LIBRARY_DIR=$HOME/progs/libav/lib
         -DQSCINTILLA_INCLUDE_DIR=`echo $HOME/progs/QScintilla_gpl-2.*.*/Qt4Qt5`
         -DQSCINTILLA_LIBRARY=`echo $HOME/progs/QScintilla_gpl-2.*.*/Qt4Qt5/libqscintilla2_qt5.dylib`
         -DnetCDF_DIR=$HOME/progs/netcdf/lib/cmake/netCDF
         -DHDF5_DIR=$HOME/progs/hdf5/share/cmake/hdf5
         -Dospray_DIR=`echo $HOME/progs/ospray_install/lib/cmake/ospray-*.*.*`
         -Dembree_DIR=`echo $HOME/progs/embree_install/lib/cmake/embree-*.*.*`
         -DTBB_ROOT=`echo $HOME/progs/tbb*oss`
         -DISPC_EXECUTABLE=`echo $HOME/progs/ispc-*/ispc`
         ..
      - make
      - ctest --output-on-failure
      - cpack
      - sshpass -v -e sftp ovito.org:testing/ <<< $'put ovito-*.dmg'

# This pipeline job generates the redistributable program package for Windows.
build_windows_package:
   stage: build
   tags:
      - windows_vm
   only:
      refs:
         - master
         - schedules
   artifacts:
      paths:
         - build/ovito-*.zip
         - build/ovito-*.exe
   script:
      - export PATH="/cygdrive/c/Qt/5.12.5/msvc2017_64/bin:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/HostX64/x64:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/bin/Roslyn:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Windows Kits/10/bin/x64:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin:$PATH"
      - export PATH="/cygdrive/c/Windows/Microsoft.NET/Framework64/v4.0.30319:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE:$PATH"
      - export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools:$PATH"
      - export PATH="/cygdrive/c/Perl64/site/bin:$PATH"
      - export PATH="/cygdrive/c/Program Files/CMake/bin:$PATH"
      - export PATH="/cygdrive/c/Program Files/Git LFS:$PATH"
      - export PATH="/cygdrive/c/Users/stuko/ovito/deps/Python/Scripts:$PATH"
      - export INCLUDE="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\include;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\cppwinrt;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\include;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\cppwinrt"
      - export LIB="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64;"
      - export LIBPATH="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\lib\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\lib\\x86\\store\\references;C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17763.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.17763.0;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\lib\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\lib\\x86\\store\\references;C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17763.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.17763.0;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;"
      - export Platform=x64
      - export VCINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\"
      - export VCToolsInstallDir="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\Tools\\MSVC\\14.21.27702\\"
      - export VCToolsRedistDir="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\Redist\\MSVC\\14.21.27702\\"
      - export VCToolsVersion=14.21.27702
      - export VisualStudioVersion=16.0
      - export VSINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\"
      - export windir="C:\\WINDOWS"
      - export WindowsLibPath="C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17763.0;C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.17763.0"
      - export WindowsSdkBinPath="C:\\Program Files (x86)\\Windows Kits\\10\\bin\\"
      - export WindowsSdkDir="C:\\Program Files (x86)\\Windows Kits\\10\\"
      - export WindowsSDKLibVersion=10.0.17763.0
      - export WindowsSdkVerBinPath="C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\"
      - export WindowsSDKVersion=10.0.17763.0
      - mkdir build
      - cd build
      - cmake -G "NMake Makefiles"
         -DCMAKE_BUILD_TYPE=Release
         -DCMAKE_INSTALL_PREFIX=../release_install
         -DOVITO_REDISTRIBUTABLE_PACKAGE=ON
         -DZLIB_INCLUDE_DIR=$USERPROFILE/ovito/deps/zlib/include
         -DZLIB_LIBRARY=$USERPROFILE/ovito/deps/zlib/lib/zlib.lib
         -Dnetcdf_DIR=$USERPROFILE/ovito/deps/netcdf/lib/cmake/netCDF
         -DHDF5_DIR=$USERPROFILE/ovito/deps/hdf5/cmake/hdf5
         -DBOOST_INCLUDEDIR=$USERPROFILE/ovito/deps/boost_1_70_0
         -DQSCINTILLA_INCLUDE_DIR=$USERPROFILE/ovito/deps/QScintilla_gpl-2.11.2/Qt4Qt5
         -DQSCINTILLA_LIBRARY=$USERPROFILE/ovito/deps/qscintilla/release/qscintilla2_qt5.lib
         -DPYTHON_LIBRARY=$USERPROFILE/ovito/deps/Python/libs/python37.lib
         -DPYTHON_INCLUDE_DIR=$USERPROFILE/ovito/deps/Python/include
         -DPYTHON_EXECUTABLE=$USERPROFILE/ovito/deps/Python/python.exe
         -DXSLT_PROCESSOR=$USERPROFILE/ovito/deps/libxslt-1.1.26.win32/bin/xsltproc.exe
         -DLIBAV_INCLUDE_DIR=$USERPROFILE/ovito/deps/libav/include
         -DLIBAV_LIBRARY_DIR=$USERPROFILE/ovito/deps/libav/bin
         -DOVITO_BUILD_DOCUMENTATION=ON
         -DOVITO_BUILD_MONOLITHIC=ON
         -DOVITO_BUILD_PLUGIN_VR=OFF
         -DOVITO_DOUBLE_PRECISION_FP=ON
         -DOPENVR_INCLUDE_DIR=$USERPROFILE/ovito/deps/openvr/headers
         -DOPENVR_LIBRARY=$USERPROFILE/ovito/deps/openvr/lib/win64/openvr_api.lib
         -DLIBSSH_INCLUDE_DIR=$USERPROFILE/ovito/deps/libssh/include
         -DLIBSSH_LIBRARY=$USERPROFILE/ovito/deps/libssh/lib/ssh.lib
         -DOPENSSL_ROOT_DIR=$USERPROFILE/ovito/deps/openssl
         -DOVITO_BUILD_PLUGIN_OSPRAY=ON
         -Dospray_DIR=$USERPROFILE/ovito/deps/ospray/lib/cmake/ospray-1.8.5
         -Dembree_DIR=$USERPROFILE/ovito/deps/embree
         -DTBB_ROOT=$USERPROFILE/ovito/deps/embree-3.5.2/tbb
         -DTBB_DIR=$USERPROFILE/ovito/deps/embree-3.5.2/tbb/cmake
         -DISPC_EXECUTABLE=$USERPROFILE/ovito/deps/ispc/bin/ispc.exe
         ..
      - nmake
      #- ctest --output-on-failure  # Disabled for now, because Windows 10 VM guests don't support OpenGL 2.1+, which is needed for the tests.
      - cpack
      - cpack -G ZIP
      - timeout 30s sshpass -v -e sftp ovito.org:testing/ <<< $'put ovito-*.zip'
      - timeout 30s sshpass -v -e sftp ovito.org:testing/ <<< $'put ovito-*.exe'