image: registry.gitlab.com/stuko/ovito/linux_build:latest

build_linux_python3:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DPYTHON_EXECUTABLE=/usr/bin/python3.5
           -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j3 install
      - ctest --output-on-failure
      - linkchecker --check-extern ../install/share/ovito/doc/manual/html/index.html
           --ignore-url=https://dx.doi.org/10.1088/0965-0393/24/5/055007
           --ignore-url=http://stacks.iop.org/0965-0393/18/015012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/3/035012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/4/045021
           --ignore-url=http://dx.doi.org/10.1038/nature04421

build_linux_python2:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DPYTHON_EXECUTABLE=/usr/bin/python2.7
           -DPYTHON_INCLUDE_DIR=/usr/include/python2.7
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j3 install
      - ctest --output-on-failure

# This pipeline job generates the redistributable program package for Linux.
build_linux_package:
   stage: build
   tags:
      - linux_vm
   script:
      - ls -a
      - git describe
      - mkdir build
      - cd build
      - export LD_LIBRARY_PATH=$HOME/progs/libav/lib:$LD_LIBRARY_PATH
      - cmake
         -DOVITO_BUILD_DOCUMENTATION=ON
         -DCMAKE_BUILD_TYPE=Release
         -DCMAKE_INSTALL_PREFIX=../release_install
         -DOVITO_REDISTRIBUTABLE_PACKAGE=ON
         -DOVITO_DOUBLE_PRECISION_FP=ON
         -DOVITO_BUILD_PLUGIN_OSPRAY=ON
         -DHDF5_DIR=$HOME/progs/hdf5/share/cmake/hdf5
         -DnetCDF_DIR=$HOME/progs/netcdf/lib/cmake/netCDF
         -DPYTHON_EXECUTABLE=$HOME/progs/python/bin/python3
         -DPYTHON_LIBRARY=`echo $HOME/progs/python/lib/libpython*.so.*`
         -DPYTHON_INCLUDE_DIR=`echo $HOME/progs/python/include/python*`
         -DCMAKE_PREFIX_PATH=$HOME/progs/qt5/
         -DQSCINTILLA_INCLUDE_DIR=`echo $HOME/progs/QScintilla_gpl-*`/Qt4Qt5/
         -DQSCINTILLA_LIBRARY=`echo $HOME/progs/QScintilla_gpl-*/Qt4Qt5/libqscintilla2_qt5.so.*`
         -DLIBAV_INCLUDE_DIR=$HOME/progs/libav/include
         -DLIBAV_LIBRARY_DIR=$HOME/progs/libav/lib
         -Dospray_DIR=`echo $HOME/progs/ospray_install/lib/cmake/ospray-*`
         -Dembree_DIR=`echo $HOME/progs/embree_install/lib/cmake/embree-*`
         -DISPC_EXECUTABLE=`echo $HOME/progs/ispc-*-linux/ispc`
         -DTBB_INCLUDE_DIR=`echo $HOME/progs/tbb*oss`/include/
         -DTBB_LIBRARY=`echo $HOME/progs/tbb*oss`/lib/intel64/gcc4.7/libtbb.so
         -DTBB_LIBRARY_MALLOC=`echo $HOME/progs/tbb*oss`/lib/intel64/gcc4.7/libtbbmalloc.so
         -DTBB_DIR=`echo $HOME/progs/tbb*oss`/cmake
         -DTBB_ROOT=`echo $HOME/progs/tbb*oss`
         -DLIBSSH_INCLUDE_DIR=$HOME/progs/libssh/include
         -DLIBSSH_LIBRARY=$HOME/progs/libssh/lib/libssh.so
         ..
      - make
      - cpack

# This pipeline job generates the redistributable program package for MacOS.
build_macos_package:
    stage: build
    tags:
       - macos_vm
    script:
       - mkdir build
       - cd build
       - cmake
         -DOVITO_BUILD_DOCUMENTATION=ON
         -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12
         -DCMAKE_BUILD_TYPE=Release
         -DOVITO_REDISTRIBUTABLE_PACKAGE=ON
         -DOVITO_DOUBLE_PRECISION_FP=ON
         -DOVITO_BUILD_PLUGIN_OSPRAY=ON
         -DCMAKE_INSTALL_PREFIX=../release_install
         -DCMAKE_PREFIX_PATH=`echo $HOME/Qt/5.*.*/clang_64/`
         -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
         -DPYTHON_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m
         -DPYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib
         -DLIBAV_INCLUDE_DIR=$HOME/progs/libav/include
         -DLIBAV_LIBRARY_DIR=$HOME/progs/libav/lib
         -DQSCINTILLA_INCLUDE_DIR=`echo $HOME/progs/QScintilla_gpl-2.*.*/Qt4Qt5`
         -DQSCINTILLA_LIBRARY=`echo $HOME/progs/QScintilla_gpl-2.*.*/Qt4Qt5/libqscintilla2_qt5.dylib`
         -DnetCDF_DIR=$HOME/progs/netcdf/lib/cmake/netCDF
         -DHDF5_DIR=$HOME/progs/hdf5/share/cmake/hdf5
         -Dospray_DIR=`echo $HOME/progs/ospray_install/lib/cmake/ospray-*.*.*`
         -Dembree_DIR=`echo $HOME/progs/embree_install/lib/cmake/embree-*.*.*`
         -DTBB_ROOT=`echo $HOME/progs/tbb*oss`
         -DISPC_EXECUTABLE=`echo $HOME/progs/ispc-*/ispc`
         ..
       - make
       - ctest --output-on-failure
       - cpack
