image: registry.gitlab.com/stuko/ovito/linux_build:latest

test_linux:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      - make -j2 install
      - ../install/bin/ovito --nogui
      - ctest --output-on-failure
      - linkchecker --check-extern ../install/share/ovito/doc/manual/html/index.html
           --ignore-url=https://dx.doi.org/10.1088/0965-0393/24/5/055007
           --ignore-url=http://stacks.iop.org/0965-0393/18/015012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/3/035012
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/4/045021
           --ignore-url=http://dx.doi.org/10.1038/nature04421
           --ignore-url=http://dx.doi.org/10.1088/0965-0393/20/8/085007
           --ignore-url=http://stacks.iop.org/0965-0393/20/085007
