image: ubuntu:latest

before_script:
  - apt-get update -y -q
  - apt-get install -y cmake

build_linux:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug ..
      - make